<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS XML DOCUMENT CONTAINS YOUR ENCRYPTED LICENSE KEY.
	DO NOT EDIT MANUALLY. LICENSE KEYS ARE UNIQUE FOR EACH
	INSTALLATION OF HOMEPORTALS AND WILL NOT WORK ON OTHER
	SERVERS.
	
	FOR QUESTIONS AND/OR PURCHASE NEW LICENSE KEYS
	CONTACT CFEmpire Corp. at info@cfempire.com
--><license>
	<licenseKey></licenseKey>
	<expiresOn></expiresOn>
	<adminPwd>21232F297A57A5A743894A0E4A801FC3</adminPwd>
</license>
